import { Share } from "@capacitor/share";
import { Filesystem, Directory } from "@capacitor/filesystem";
import { isNative } from "./platform";

/**
 * 리포트를 공유용 카드 이미지(PNG)로 렌더링.
 * 1080x1350 세로 (인스타/스레드 최적), 다크 뉴트럴 + 앰버 악센트.
 */

const W = 1080;
const H = 1350;

const FONT_SANS = '"Inter", "Pretendard Variable", "Pretendard", -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif';

function wrap(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const lines: string[] = [];
  const paragraphs = text.split("\n");
  for (const p of paragraphs) {
    if (p.trim() === "") {
      lines.push("");
      continue;
    }
    let line = "";
    for (const ch of p) {
      const test = line + ch;
      if (ctx.measureText(test).width > maxWidth && line.length > 0) {
        lines.push(line);
        line = ch;
      } else {
        line = test;
      }
    }
    if (line) lines.push(line);
  }
  return lines;
}

export async function renderMemorialCard(params: {
  title: string;
  body: string;
}): Promise<Blob | null> {
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d");
  if (!ctx) return null;

  // 배경
  ctx.fillStyle = "#0A0A0B";
  ctx.fillRect(0, 0, W, H);

  // 카드 패널
  const pad = 72;
  const panelX = pad;
  const panelY = pad;
  const panelW = W - pad * 2;
  const panelH = H - pad * 2;

  ctx.fillStyle = "#141517";
  roundRect(ctx, panelX, panelY, panelW, panelH, 16);
  ctx.fill();

  ctx.strokeStyle = "#26282C";
  ctx.lineWidth = 1;
  roundRect(ctx, panelX, panelY, panelW, panelH, 16);
  ctx.stroke();

  // 상단 브랜드
  ctx.fillStyle = "#E89A3C";
  ctx.font = `600 24px ${FONT_SANS}`;
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillText("HOJO", panelX + 56, panelY + 56);

  ctx.fillStyle = "#7A7D82";
  ctx.font = `500 18px ${FONT_SANS}`;
  ctx.fillText("FINANCE REPORT", panelX + 56, panelY + 92);

  // 제목
  ctx.fillStyle = "#E8EAED";
  ctx.font = `700 42px ${FONT_SANS}`;
  ctx.textAlign = "left";
  ctx.fillText(params.title, panelX + 56, panelY + 160);

  // 구분선
  ctx.strokeStyle = "#26282C";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(panelX + 56, panelY + 232);
  ctx.lineTo(panelX + panelW - 56, panelY + 232);
  ctx.stroke();

  // 본문
  ctx.fillStyle = "#C7CACF";
  ctx.font = `400 26px ${FONT_SANS}`;
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  const bodyX = panelX + 56;
  const bodyY = panelY + 270;
  const bodyMaxW = panelW - 112;
  const lineH = 42;
  const lines = wrap(ctx, params.body, bodyMaxW);
  const maxLines = Math.floor((panelH - (bodyY - panelY) - 120) / lineH);
  const shown = lines.slice(0, maxLines);
  shown.forEach((ln, i) => {
    ctx.fillText(ln, bodyX, bodyY + i * lineH);
  });

  // 하단 엑센트 바
  ctx.fillStyle = "#E89A3C";
  ctx.fillRect(panelX + 56, H - pad - 72, 48, 3);

  // 푸터
  ctx.fillStyle = "#7A7D82";
  ctx.font = `500 18px ${FONT_SANS}`;
  ctx.textAlign = "left";
  ctx.fillText("Generated by Hojo", panelX + 56, H - pad - 56);

  return new Promise<Blob | null>((resolve) => {
    canvas.toBlob((b) => resolve(b), "image/png", 0.95);
  });
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number, r: number,
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => {
      const s = String(r.result);
      const i = s.indexOf(",");
      resolve(i >= 0 ? s.slice(i + 1) : s);
    };
    r.onerror = () => reject(r.error);
    r.readAsDataURL(blob);
  });
}

export async function shareMemorial(params: {
  title: string;
  body: string;
  filename?: string;
}) {
  const blob = await renderMemorialCard(params);
  if (!blob) return;
  const filename = params.filename ?? "hojo-report.png";

  if (isNative()) {
    try {
      const base64 = await blobToBase64(blob);
      const written = await Filesystem.writeFile({
        path: filename,
        data: base64,
        directory: Directory.Cache,
      });
      await Share.share({
        title: params.title,
        files: [written.uri],
        dialogTitle: params.title,
      });
      return;
    } catch (err) {
      if (err instanceof Error && /cancel/i.test(err.message)) return;
      console.warn("[share] native failed, fallback:", err);
    }
  }

  const file = new File([blob], filename, { type: "image/png" });
  if (navigator.canShare && navigator.canShare({ files: [file] })) {
    try {
      await navigator.share({ files: [file], title: params.title });
      return;
    } catch {
      // fallthrough to download
    }
  }
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = file.name;
  a.click();
  URL.revokeObjectURL(url);
}
